### ISSUE TITLE
A proposal for using the return value as the response body

### ISSUE THREAD

**Issue by luin** [trekjs/trek#13]
Trek uses the `body` property of the context as the response body (like Koa), which seems to be a little unintuitive considering generators are used in favor of callbacks. I was wondering if the return value of the controller function could be used as the response body. For instance, if we want to return a json object representing a user:

```javascript
app.get('/users/:id', function *() {
  return yield User.find(this.params.id);
});
```

Anyway, just a random thought. Trek seems promising :-)

**Comment by fundon** [comment]
Yup, `Trek` extends the `Koa`, so the behavior is that using `body` for the response.

Sounds good. Likes this https://github.com/gulpjs/gulp/commit/5a2ec1b1a6633f830bd4a2b1daab578c062e6975.

I like this idea, 👍. I will try to realize it.

**Comment by fundon** [comment]
@luin Landed in https://github.com/trekjs/trek/blob/master/src/Engine.js#L201-L206.

**Comment by luin** [comment]
That was fast! Awesome :+1:
