### ISSUE TITLE
warn: [Trek]    Load the routes failed, ReferenceError: get is not defined.

### ISSUE THREAD

**Issue by nitetrik** [trekjs/trek#73]
I get this Warning, In the routes file the get function is not defined?

**Comment by alexey-m-ukolov** [comment]
Yeah, I have this problem too.
Possibly [this change](https://github.com/trekjs/cli/commit/59b082af619e88601aed60c9ec974438b1b0fadb#diff-9ee412a761249a4fb57e79e37014c032R2) broke something?

**Comment by fundon** [comment]
Thanks, I checking.

**Comment by fundon** [comment]
Now, I'm working in the next branch.
