### ISSUE TITLE
React Style Component

### ISSUE THREAD

**Issue by fundon** [trekjs/trek#8]
I love the component.

**Comment by coolicer** [comment]
如果使用了吗？

**Comment by fundon** [comment]
还没，在想使用场景，如何简单、方便且实用

**Comment by coolicer** [comment]
@fundon 其实我是想问，这个项目可以用没。不是react这块。

**Comment by fundon** [comment]
在用呀，目前在开发个人站 
源码：https://github.com/FuturespaceIO/futurespace
在线地址：https://futurespaceio.herokuapp.com 
线上的还只有简单几个路由： `/login`, `/signup`, `/signout`.
