### ISSUE TITLE
Customize Template Engine

### ISSUE THREAD

**Issue by fundon** [trekjs/trek#9]

**Comment by coolicer** [comment]
挖坑速度好快。还有db也要可以自定义吧

想问一下，config/routes.js 这里的routes是放所有的路由吗？

**Comment by fundon** [comment]
db 目前就是开发的

是的，`config/routes.js` 是放所有的路由

**Comment by fundon** [comment]
整体上你可以看到很多 Rails 的影子，哈哈，我借鉴了很多

**Comment by coolicer** [comment]
@fundon 看了一下config/database.js，好像这里只是选用了sequelizejs。如果你选mongoose，也在这里配置吗？

**Comment by fundon** [comment]
嗯，约定 `config/database.js` 放数据库（sql or nosql）的基本配置。

当然，这里你也可以自己定已，然后 DIY 下。（抱歉文档还比较少，如果需要你得看源码了）

**Comment by coolicer** [comment]
那个sequelizejs的migrations正确用法是什么？
比如我之前做过一个半成品。我在model删除一些字段（字段），然后数据库表里面还会有这个字段。

然后用migrations去删除字段，不知道是不是这样用。另外，后来发现在个sync({force: true})。不知道是不是可以做到在model里删除属性，可以同步到数据库。

**Comment by fundon** [comment]
`sync({force: true})` 这个是你在开发早期，还没多少数据，且频繁更改数据库结构的情况下使用的；
线上，数据多请务必关掉。（会删掉所有数据）

migrations： 写 `up` 和 `down` 操作，结构有改动就用，执行下命令，也可以回退，正确的用法是，感觉结构不是你想要的，就要开启下一个 `migration`，不要一直回退。

**Comment by coolicer** [comment]
@fundon 原来down是用来恢复的，明白了。谢谢

**Comment by fundon** [comment]
试下你就知道了，:)

**Comment by fundon** [comment]
app.render => context.render
